manual/mkdocs/mkdocs.nuspec
Fix package source URL and some more tags
=> Fixes for the MkDocs package

automatic/bower/bower.nuspec, automatic/gulp-cli/gulp-cli.nuspec, automatic/mkdocs/mkdocs.nuspec
Add files explicitely to the manifest to avoid ending update.ps1 as part of the package
=> Add files explicitely to the manifest

.appveyor.yml
There was some error commiting changes made through AU back to Git. Update GitHub token and Git username
=> Update GitHub token and Git username

automatic/bower/bower.nuspec, automatic/gulp-cli/gulp-cli.nuspec
Update package source and icon to new URL
=> Update URL to package source and icon

automatic/gulp-cli/gulp-cli.nuspec
Change dependency to nodejs meta package
=> (gulp-cli) Change dependency to nodejs meta package

automatic/bower/bower.nuspec
Change dependency to nodejs meta package
=> (bower) Change dependency to nodejs meta package

automatic/markdownlint-cli/markdownlint-cli.nuspec, automatic/markdownlint-cli/tools/chocolateyInstall.ps1, automatic/markdownlint-cli/tools/chocolateyUninstall.ps1, automatic/markdownlint-cli/update.ps1
Add new package for globally installing markdownlint-cli
=> (markdownlint-cli) Add package

automatic/bower/bower.nuspec
Set correct min version of Node.Js based on [project source code](https://github.com/bower/bower/blob/master/package.json#L12).
=> (bower) Set min version of NodeJs

scripts/Update-IconUrl.ps1
Fixes URL of GitHub repository in icon update script
=> Fix GitHub repository url

scripts/Test-RepoPackage.ps1
Make sure that packages are created before nupkg file path is evaluated
=> Make sure that packages are created before nupkg file path is evaluated

manual/vscode-codespellchecker/vscode-codespellchecker.nuspec
Only include tool files in package
=> (vscode-codespellchecker) Only include tool files in package

manual/vscode-codespellchecker/vscode-codespellchecker.nuspec
=> (vscode-codespellchecker) Make tags lower-case

manual/vscode-codespellchecker-german/vscode-codespellchecker-german.nuspec
=> (vscode-codespellchecker-german) Fix title

manual/vscode-cake/README.md, manual/vscode-cake/update.ps1, manual/vscode-cake/vscode-cake.nuspec, manual/vscode-codespellchecker-german/README.md, manual/vscode-eslint/README.md, manual/vscode-eslint/update.ps1, manual/vscode-eslint/vscode-eslint.nuspec, manual/vscode-gitlens/README.md, manual/vscode-gitlens/update.ps1, manual/vscode-markdownlint/README.md, manual/vscode-markdownlint/update.ps1, manual/vscode-markdownlint/vscode-markdownlint.nuspec
Update dependencies, description, tags and links of Visual Studio Code extensions
=> (vscode-*) Update metadata

.appveyor.yml
Use default image (Visual Studio 2015)
=> Use default image

automatic/bower/update.ps1, automatic/gulp-cli/update.ps1, automatic/markdownlint-cli/update.ps1
Use basic parsing in update scripts
=> Use basic parsing in update scripts

automatic/bower/bower.nuspec, automatic/bower/update.ps1
This allows to use it with either the nodejs or nodejs-lts package.
=> (bower) Remove dependency to NodeJs

automatic/markdownlint-cli/README.md, automatic/markdownlint-cli/markdownlint-cli.nuspec
Add icon to README and package
=> Add icon to README and package

.appveyor.yml
Use latest AU release instead of latest master build to avoid being affected by https://github.com/majkinetor/au/issues/181
=> Use latest AU release instead of latest master build

.appveyor.yml
Fixes a typo in AppVeyor build script
=> Fix typo in AppVeyor build script

.appveyor.yml
Add screenshot artifacts on pull requests
=> Add screenshot artifacts on pull requests

scripts/Test-RepoPackage.ps1, scripts/Update-IconUrl.ps1, scripts/Update-PackageSourceUrl.ps1, test_all.ps1, update_all.ps1
=> Update build & test scripts

.appveyor.yml
Update version of Chocolatey and AU helpers to use
=> Update version of Chocolatey and AU helpers to use

.appveyor.yml
=> Save test results

.appveyor.yml
Disable mail notification as required credentials were not set
=> Disable mail notification

.appveyor.yml
Provide Chocolatey logs as artifacts
=> Provide Chocolatey logs as artifacts

manual/azure-data-studio-sql-server-admin-pack/README.md, manual/azure-data-studio-sql-server-admin-pack/azure-data-studio-sql-server-admin-pack.nuspec
Improve package metadata for azure-data-studio-sql-server-admin-pack
=> (azure-data-studio-sql-server-admin-pack) Improve package metadata

test_all.ps1, update_all.ps1
Increase log output in case of errors during update
=> Increase log output in case of errors during update

azure-pipelines.yml
Make sure artifacts are published on build failure
=> Publish artifacts on build failure

manual/dotnet4.7.2-deu/README.md, manual/dotnet4.7.2-deu/dotnet4.7.2-deu.nuspec, manual/dotnet4.7.2-deu/tools/chocolateyInstall.ps1, manual/dotnet4.7.2-deu/update.ps1
Add package for german language pack for .NET 4.7.2
=> (dotnet4.7.2-deu) Add package for german language pack for .NET 4.7.2

manual/dotnet4.7.2-deu/dotnet4.7.2-deu.nuspec
Remove README.md and update.ps1 script from package
=> (dotnet4.7.2-deu) Remove README and update script from package

automatic/bower/tools/chocolateyInstall.ps1, automatic/gulp-cli/tools/chocolateyInstall.ps1, automatic/markdownlint-cli/tools/chocolateyInstall.ps1
If Node.js is not installed output a message with instructions how to install
Fixes #53
=> (GH-53) Check if Node.js is installed

automatic/ssis-vs2019/ssis-vs2019.nuspec
Add requirements as dependency or to package description
Fixes #76
=> (GH-76) (ssis-vs2019) Add requirements as dependency or to description

automatic/ssis-vs2019/readme.md, automatic/ssis-vs2019/ssis-vs2019.nuspec
Update README to current package description as package description will be overriden from the README during build.
=> (ssis-vs2019) Update README to current description

manual/vscode-cake/vscode-cake.nuspec
Not sure if this is correct. The numbers might need to be changed if I didn't input them correctly based on the package versioning. Let me know what you think. I ran the script to install but not really sure how to validate it since I have vscode installed already. 
Fixes #81
=> (GH-81) Added dependency to check for anything above 1.0 but less than 2.0

automatic/ssis-vs2019/ssis-vs2019.nuspec
Fix version number ssis package to the version currently published to chocolatey.org
=> Fix version number ssis package

azure-pipelines.yml
Increase timeout for build to avoid failing builds.
=> Increase timeout for build

extensions/chocolatey-npm.extension/README.md, extensions/chocolatey-npm.extension/chocolatey-npm.extension.nuspec
Add missing README and fix metadata
=> Add missing README and fix metadata

automatic/markdownlint-cli/markdownlint-cli.nuspec, automatic/markdownlint-cli/tools/chocolateyInstall.ps1, automatic/markdownlint-cli/tools/chocolateyUninstall.ps1
Support installation through background service
FIxes #96
=> (GH-96) Support installation through background service

automatic/gulp-cli/gulp-cli.nuspec, automatic/gulp-cli/tools/chocolateyInstall.ps1, automatic/gulp-cli/tools/chocolateyUninstall.ps1
Support installation through background service
FIxes #97
=> (GH-97) Support installation through background service

automatic/ssis-vs2019/update.ps1
Fix update script for ssis-vs2019 package
=> (ssis-vs2019) Fix update

manual/vscode-markdown-all-in-one/README.md, manual/vscode-markdown-all-in-one/tools/ChocolateyInstall.ps1, manual/vscode-markdown-all-in-one/tools/chocolateyUninstall.ps1, manual/vscode-markdown-all-in-one/update.ps1, manual/vscode-markdown-all-in-one/vscode-markdown-all-in-one.nuspec
Add VSCode Markdown All In One Package
=> Add VSCode Markdown All In One Package

manual/vscode-xmltools/README.md, manual/vscode-xmltools/tools/ChocolateyInstall.ps1, manual/vscode-xmltools/tools/ChocolateyUninstall.ps1, manual/vscode-xmltools/update.ps1, manual/vscode-xmltools/vscode-xmltools.nuspec
Add new VSCode Package for XML Tools Extension
=> Add vscode-xmltools

azure-pipelines.yml
Image details: Windows Server 2022 with Visual Studio 2022
=> Update VmImage to windows-2022

automatic/gulp-cli/update.ps1
Fixes updating of bower package by using PowerShellForGitHub module.
=> (gulp-cli) Fix update of package

automatic/bower/update.ps1
Fixes updating of bower package by using PowerShellForGitHub module.
=> (bower) Fix update of package

automatic/ssis-vs2022/ssis-vs2022.nuspec, automatic/ssis-vs2022/tools/ChocolateyInstall.ps1
Use Install-VisualStudioVsixExtension from chocolatey-visualstudio.extension package to install the extension
Added reference to chocolatey-visualstudio.extension version 1.11.
=> Use Install-VisualStudioVsixExtension to install the extension
